### ISSUE TITLE
Test doesn't build with GHC 9.6

### ISSUE THREAD

**Issue by chris-martin** [pbrisbin/yaml-marked#1]
```
test/Data/Yaml/Marked/DecodeSpec.hs:36:3: error: [GHC-39999]
    • No instance for ‘GHC.Base.Alternative (Either String)’
        arising from a use of ‘asum’
    • In the expression:
        asum [fmap Git <$> decodeGitCommit x, fmap Plain <$> text x]
      In an equation for ‘decodeExtraDep’:
          decodeExtraDep x
            = asum [fmap Git <$> decodeGitCommit x, fmap Plain <$> text x]
   |
36 |   asum
   |   ^^^^
```
